# SVD Schritt für Schritt

In diesem Notebook berechnen wir die Singulärwertzerlegung zuerst an einer kleinen Matrix per Hand nach.

Danach vergleichen wir das Ergebnis mit der fertigen NumPy-Funktion `np.linalg.svd`.

Ziel ist der Zusammenhang

$$
A = U\Sigma V^T
$$

und die Bausteinform

$$
A = \sum_i \sigma_i u_i v_i^T.
$$

## 1. Setup

In [60]:
import numpy as np

np.set_printoptions(precision=4, suppress=True)

## 2. Beispielmatrix

Wir verwenden die kleine Matrix

$$
A=
\begin{pmatrix}
2 & 2\\
1 & -1
\end{pmatrix}.
$$

Diese Matrix ist klein genug, um die SVD Schritt für Schritt nachzurechnen.

Wir betrachten $A$ als lineare Abbildung

$$
A:\mathbb{R}^2\to\mathbb{R}^2.
$$

In [73]:
A = np.array([
    [2,  2],
    [1, -1]
], dtype=float)

print("A =")
print(A)
print("Form von A:", A.shape)

A =
[[ 2.  2.]
 [ 1. -1.]]
Form von A: (2, 2)


## 3. Schritt 1: $A^TA$ berechnen

Für die SVD starten wir mit

$$
A^TA.
$$

Zuerst ist

$$
A^T=
\begin{pmatrix}
2 & 1\\
2 & -1
\end{pmatrix}.
$$

Damit ergibt sich

$$
A^TA=
\begin{pmatrix}
2 & 1\\
2 & -1
\end{pmatrix}
\begin{pmatrix}
2 & 2\\
1 & -1
\end{pmatrix}
=
\begin{pmatrix}
5 & 3\\
3 & 5
\end{pmatrix}.
$$

Diese Matrix ist quadratisch und symmetrisch. Deshalb können wir auf $A^TA$ den Spektralsatz anwenden.

In [74]:
ATA = A.T @ A

print("A^T A =")
print(ATA)
print("Ist A^T A symmetrisch?", np.allclose(ATA, ATA.T))

A^T A =
[[5. 3.]
 [3. 5.]]
Ist A^T A symmetrisch? True


## 4. Schritt 2: Eigenwerte von $A^TA$

Die Eigenwerte von $A^TA$ erhalten wir aus

$$
\det(A^TA-\lambda I)=0.
$$

Hier ist

$$
A^TA-\lambda I=
\begin{pmatrix}
5-\lambda & 3\\
3 & 5-\lambda
\end{pmatrix}.
$$

Also:

$$
\det(A^TA-\lambda I)
=
(5-\lambda)^2-9.
$$

Die Gleichung

$$
(5-\lambda)^2-9=0
$$

liefert

$$
\lambda_1=8,
\qquad
\lambda_2=2.
$$

Wichtig: $\lambda_i$ sind hier **Eigenwerte von $A^TA$**.

In [75]:
eigvals, eigvecs = np.linalg.eigh(ATA)

# eigh sortiert aufsteigend. Für die SVD sortieren wir absteigend.
idx = np.argsort(eigvals)[::-1]
eigvals = eigvals[idx]
eigvecs = eigvecs[:, idx]

print("Eigenwerte von A^T A:")
print(eigvals)

Eigenwerte von A^T A:
[8. 2.]


## 5. Schritt 3: Singulärwerte berechnen

Die Singulärwerte von $A$ sind die Wurzeln der Eigenwerte von $A^TA$:

$$
\sigma_i=\sqrt{\lambda_i}.
$$

Also:

$$
\sigma_1=\sqrt{8}=2\sqrt{2},
\qquad
\sigma_2=\sqrt{2}.
$$

Kurz gesagt:

$$
\lambda_i=\sigma_i^2.
$$

In [76]:
sigma = np.sqrt(eigvals)

print("Singulärwerte sigma_i:")
print(sigma)

Singulärwerte sigma_i:
[2.8284 1.4142]


## 6. Schritt 4: Eigenvektoren $v_i$

Für $\lambda_1=8$ lösen wir

$$
A^TA v_1 = 8v_1.
$$

Ein normierter Eigenvektor ist

$$
v_1=\frac{1}{\sqrt{2}}
\begin{pmatrix}
1\\
1
\end{pmatrix}.
$$

Für $\lambda_2=2$ erhalten wir

$$
v_2=\frac{1}{\sqrt{2}}
\begin{pmatrix}
1\\
-1
\end{pmatrix}.
$$

Damit ist

$$
V=
\begin{pmatrix}
\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}}\\
\frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}}
\end{pmatrix}.
$$

Die Spalten von $V$ sind die Eigenvektoren von $A^TA$.

In [77]:
sqrt2 = np.sqrt(2)

V = np.array([
    [1/sqrt2,  1/sqrt2],
    [1/sqrt2, -1/sqrt2]
])

print("V =")
print(V)
print("\nKontrolle V^T V =")
print(V.T @ V)
print("\nKontrolle A^T A V =")
print(ATA @ V)
print("\nV diag(lambda) =")
print(V @ np.diag(eigvals))

V =
[[ 0.7071  0.7071]
 [ 0.7071 -0.7071]]

Kontrolle V^T V =
[[ 1. -0.]
 [-0.  1.]]

Kontrolle A^T A V =
[[ 5.6569  1.4142]
 [ 5.6569 -1.4142]]

V diag(lambda) =
[[ 5.6569  1.4142]
 [ 5.6569 -1.4142]]


## 7. Schritt 5: Höhenverteilungen $u_i$

Jetzt berechnen wir

$$
u_i=\frac{Av_i}{\sigma_i}.
$$

Für den ersten Eigenvektor gilt:

$$
Av_1
=
\begin{pmatrix}
2 & 2\\
1 & -1
\end{pmatrix}
\frac{1}{\sqrt{2}}
\begin{pmatrix}
1\\
1
\end{pmatrix}
=
\begin{pmatrix}
2\sqrt{2}\\
0
\end{pmatrix}.
$$

Da $\sigma_1=2\sqrt{2}$, folgt

$$
u_1=\frac{Av_1}{\sigma_1}
=
\begin{pmatrix}
1\\
0
\end{pmatrix}.
$$

Für den zweiten Eigenvektor gilt:

$$
Av_2
=
\begin{pmatrix}
2 & 2\\
1 & -1
\end{pmatrix}
\frac{1}{\sqrt{2}}
\begin{pmatrix}
1\\
-1
\end{pmatrix}
=
\begin{pmatrix}
0\\
\sqrt{2}
\end{pmatrix}.
$$

Da $\sigma_2=\sqrt{2}$, folgt

$$
u_2=\frac{Av_2}{\sigma_2}
=
\begin{pmatrix}
0\\
1
\end{pmatrix}.
$$

Damit ist

$$
U=
\begin{pmatrix}
1 & 0\\
0 & 1
\end{pmatrix}.
$$

In [78]:
U = np.zeros_like(A)

for i in range(len(sigma)):
    U[:, i] = (A @ V[:, i]) / sigma[i]

print("U =")
print(U)
print("\nKontrolle U^T U =")
print(U.T @ U)

U =
[[1. 0.]
 [0. 1.]]

Kontrolle U^T U =
[[1. 0.]
 [0. 1.]]


## 8. Schritt 6: $\Sigma$ aufstellen

Die Singulärwerte stehen auf der Diagonalen von $\Sigma$:

$$
\Sigma=
\begin{pmatrix}
2\sqrt{2} & 0\\
0 & \sqrt{2}
\end{pmatrix}.
$$

In [79]:
Sigma = np.diag(sigma)

print("Sigma =")
print(Sigma)

Sigma =
[[2.8284 0.    ]
 [0.     1.4142]]


## 9. Rekonstruktion: $A=U\Sigma V^T$

Jetzt setzen wir alles zusammen:

$$
A=U\Sigma V^T.
$$

Für unser Beispiel ist

$$
U=
\begin{pmatrix}
1 & 0\\
0 & 1
\end{pmatrix},
\qquad
\Sigma=
\begin{pmatrix}
2\sqrt{2} & 0\\
0 & \sqrt{2}
\end{pmatrix},
\qquad
V^T=
\begin{pmatrix}
\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}}\\
\frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}}
\end{pmatrix}.
$$

In [80]:
A_reconstructed = U @ Sigma @ V.T

print("U Sigma V^T =")
print(A_reconstructed)
print("\nStimmt die Rekonstruktion mit A überein?")
print(np.allclose(A, A_reconstructed))

U Sigma V^T =
[[ 2.  2.]
 [ 1. -1.]]

Stimmt die Rekonstruktion mit A überein?
True


## 10. Bausteinform

Die SVD kann man auch als Summe von Rang-1-Bausteinen schreiben:

$$
A=\sigma_1u_1v_1^T+\sigma_2u_2v_2^T.
$$

Der erste Baustein ist

$$
B_1=\sigma_1u_1v_1^T
=
2\sqrt{2}
\begin{pmatrix}
1\\
0
\end{pmatrix}
\frac{1}{\sqrt{2}}
\begin{pmatrix}
1 & 1
\end{pmatrix}
=
\begin{pmatrix}
2 & 2\\
0 & 0
\end{pmatrix}.
$$

Der zweite Baustein ist

$$
B_2=\sigma_2u_2v_2^T
=
\sqrt{2}
\begin{pmatrix}
0\\
1
\end{pmatrix}
\frac{1}{\sqrt{2}}
\begin{pmatrix}
1 & -1
\end{pmatrix}
=
\begin{pmatrix}
0 & 0\\
1 & -1
\end{pmatrix}.
$$

Zusammen ergibt das wieder

$$
B_1+B_2
=
\begin{pmatrix}
2 & 2\\
1 & -1
\end{pmatrix}
=A.
$$

In [69]:
blocks = []

for i in range(len(sigma)):
    B_i = sigma[i] * np.outer(U[:, i], V[:, i])
    blocks.append(B_i)
    print(f"B_{i+1} =")
    print(B_i)
    print()

print("B_1 + B_2 =")
print(blocks[0] + blocks[1])

B_1 =
[[2. 2.]
 [0. 0.]]

B_2 =
[[ 0. -0.]
 [ 1. -1.]]

B_1 + B_2 =
[[ 2.  2.]
 [ 1. -1.]]


## 11. Vergleich mit NumPy

In der Praxis berechnet man die SVD nicht per Hand, sondern mit einer Bibliotheksfunktion.

NumPy stellt dafür bereit:

```python
np.linalg.svd(A)
```

Diese Funktion liefert

$$
A=U\Sigma V^T.
$$

In NumPy wird $\Sigma$ allerdings nicht als Matrix zurückgegeben, sondern als Vektor der Singulärwerte.

In [70]:
U_np, s_np, Vt_np = np.linalg.svd(A, full_matrices=True)

print("U aus NumPy:")
print(U_np)

print("\nSingulärwerte aus NumPy:")
print(s_np)

print("\nV^T aus NumPy:")
print(Vt_np)

U aus NumPy:
[[-1. -0.]
 [-0.  1.]]

Singulärwerte aus NumPy:
[2.8284 1.4142]

V^T aus NumPy:
[[-0.7071 -0.7071]
 [ 0.7071 -0.7071]]


## 12. Rekonstruktion mit NumPy-Ergebnis

Da `np.linalg.svd` die Singulärwerte als Vektor zurückgibt, bauen wir daraus wieder eine Diagonalmatrix:

$$
\Sigma=\operatorname{diag}(\sigma_1,\sigma_2).
$$

Dann prüfen wir:

$$
A=U\Sigma V^T.
$$

In [71]:
Sigma_np = np.diag(s_np)
A_np_reconstructed = U_np @ Sigma_np @ Vt_np

print("Rekonstruktion aus NumPy-SVD:")
print(A_np_reconstructed)

print("\nStimmt das mit A überein?")
print(np.allclose(A, A_np_reconstructed))

Rekonstruktion aus NumPy-SVD:
[[ 2.  2.]
 [ 1. -1.]]

Stimmt das mit A überein?
True


## 13. Hinweis zu Vorzeichen

Die Vektoren $u_i$ und $v_i$ sind nicht eindeutig im Vorzeichen.

Wenn $u_i$ und $v_i$ gleichzeitig ihr Vorzeichen wechseln, bleibt der Baustein gleich:

$$
\sigma_i(-u_i)(-v_i)^T
=
\sigma_i u_i v_i^T.
$$

Deshalb kann NumPy Vektoren mit anderem Vorzeichen ausgeben als unsere Handrechnung. Das ist keine andere SVD im inhaltlichen Sinn.

## Fazit

Die Handrechnung zeigt die Struktur der SVD:

$$
A
\longrightarrow
A^TA
\longrightarrow
v_i
\longrightarrow
\lambda_i
\longrightarrow
\sigma_i=\sqrt{\lambda_i}
\longrightarrow
u_i=\frac{Av_i}{\sigma_i}
\longrightarrow
\sigma_i u_i v_i^T.
$$

NumPy berechnet dieselbe Zerlegung direkt mit

```python
np.linalg.svd(A)
```